# Generated by Django 3.1.7 on 2021-04-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
